{{- $values := .Values -}}
{{- $release := .Release -}}
{{- $chart := .Chart -}}
{{- range $values.apps}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $release.Name }}-{{ .name }}-deployment
  namespace: {{ $release.Namespace }}
  labels:
    chart: "{{ $chart.Name }}-{{ $chart.Version | replace "+" "-" }}"
spec:
  selector:
    matchLabels:
      app: {{ $release.Name }}-{{ .name }}-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $release.Name }}-{{ .name }}-deployment
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}:{{ .tag }}
          ports:
            - containerPort: {{ .port }}
          env:
          {{- range .env_var}}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end}}
          {{- range .secrets}}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret }}
                  key: {{ .key }}
          {{- end}}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .port | int }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .port | int }}
{{- end}}
