{{- $values := .Values -}}
{{- range $values.apps}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/redirection-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  labels:
    name: {{ $.Release.Name }}-{{ .name }}-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .hostname }}{{ $values.sha }}.{{ $values.root_domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ .name }}-service
                port:
                  number: {{ .port | int }}
{{- end}}
