{{- $values := .Values -}}
{{- $release := .Release -}}
{{- range $.Values.apps}}
{{- range .jobs}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $release.Name }}-{{ .name }}
  namespace: {{ $release.Namespace }}
  {{ if .preinstall }}
  annotations:
    argocd.argoproj.io/hook: PreSync
  {{ end }}
  {{ if .postdelete }}
  annotations:
    argocd.argoproj.io/hook: PostDelete
  {{ end }}
spec:
  template:
    spec:
      containers:
      - name: {{ $release.Name }}-{{ .name}}
        image: {{ .image }}
        command:
          {{- range .command}}
          - {{ . }}
          {{- end}}
        imagePullPolicy: Always
        env:
        {{- range .env_var}}
          - name: {{ .name }}
            value: {{ .value | quote }}
        {{- end}}
        {{- range .secrets}}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ .secret }}
                key: {{ .key }}
        {{- end}}
      restartPolicy: Never
  backoffLimit: 4
---
{{- end}}
{{- end}}
