sha: latest

root_domain: "hackthecrous.com"

apps:
  - name: "preview-backend"
    port: 80
    targetPort: 80
    image: "milou666/hackthecrous-back"
    tag: "latest"
    hostname: "api"
    jobs:
      - name: "create-database"
        image: "milou666/hackthecrous-utilities:latest"
        command: "bootstrap"
        preinstall: false # just for tests
        postinstall: false # just for tests
        env_var:
          - name: "PG_DATABASE"
            value: "htclatest"
          - name: "PG_HOST"
            value: "hackthecrous-ephemeral-postgresql.hackthecrous.svc.cluster.local"
          - name: "PG_PORT"
            value: "5432"
          - name: "PG_USER"
            value: "postgres"
          - name: "PGPASSWORD"
            value: "postgres"
        command: ["./create_preview.sh"]
    secrets:
      - name: "PG_PASSWORD"
        key: "postgres-password"
        secret: "hackthecrous-ephemeral-postgresql"
    env_var:
      - name: "PORT"
        value: "80"
      - name: "PG_DATABASE"
        value: "hackthecrous"
      - name: "PG_HOST"
        value: "0.0.0.0"
      - name: "PG_PORT"
        value: "5432"
      - name: "PG_USER"
        value: "postgres"
