apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackthecrous-backend
  namespace: services
spec:
  project: hackthecrous
  source:
    repoURL: 'https://github.com/Courtcircuits/HackTheCrous.charts'
    path: charts/backend
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - tag.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hackthecrous
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
