apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: HackTheCrous
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD project to deploy hack the crous infrastructure
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: hackthecrous
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
