apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name}}-deployment
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        env:
          - name: PORT
            value: {{ .Values.service.internalPort | quote }}
          - name: PG_DATABASE
            value: {{ .Values.postgresql.database }}
          - name: PG_HOST
            value: {{ .Values.postgresql.host | quote}}
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.secretName }}
                key: postgres-password
          - name: PG_PORT
            value: {{ .Values.postgresql.port | quote }}
          - name: PG_USER
            value: {{ .Values.postgresql.username | quote }}
          - name: SERVER_URL
            value: {{ .Values.serverUrl | quote }}

    
