apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-meals
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 6,10,11,16,18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ .Release.Name }}-update-meals"
              image: "milou666/hackthecrous-crawler:{{ .Values.image.tag }}"
              command:
                - /bin/crawler 
                - -p
                - meals
              env:
                - name: RUST_LOG
                  value: "info"
                - name: DATABASE_URL
                  value: {{ .Values.database.url | quote }}
                - name: LOKI_ENDPOINT
                  value: {{ .Values.observability.loki | quote }}
          restartPolicy: OnFailure
