apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-meals
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 6,10,11,16,18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "{{ .Release.Name }}-update-meals"
              image: "milou666/hackthecrous-crawler:{{ .Values.image.tag }}"
              command:
                - node 
                - dist/index.js
                - meals
              env:
                - name: DATABASE_URL
                  value: ""
                - name: PG_DATABASE
                  value: {{ .Values.database.name | quote }}
                - name: PG_USER
                  value: {{ .Values.database.user | quote }}
                - name: PG_HOST
                  value: {{ .Values.database.host | quote }}
                - name: PG_PORT
                  value: {{ .Values.database.port | quote }}
                - name: PG_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.database.secretName }}
                      key: postgresql-password
          restartPolicy: OnFailure
