{{- $values := .Values -}}
{{- $release := .Release -}}
{{- range $.Values.jobs}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $release.Name }}-{{ .name}}
  namespace: {{ $release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: {{ $release.Name }}-{{ .name}}
        image: "milou666/hackthecrous-crawler:{{ $values.image.tag }}"
        command: ["node", "dist/index.js", {{ .command | quote }}]
        env:
        - name: DATABASE_URL
          value: ""
        - name: PG_DATABASE
          value: {{ $values.database.name | quote }}
        - name: PG_USER
          value: {{ $values.database.user | quote }}
        - name: PG_HOST
          value: {{ $values.database.host | quote }}
        - name: PG_PORT
          value: {{ $values.database.port | quote }}
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
                name: {{ $values.database.secretName }}
                key: postgresql-password
      restartPolicy: Never
  backoffLimit: 4
---
{{- end}}